services:
  mensajero:
    image: misperception/estanteria-bot:latest
    container_name: estanteria-bot
    restart: unless-stopped
    volumes:
      - /home/misper/estanteria-bot-data:/app/data
    environment:
      - TOKEN