name: Docker Host

on:
  push:
    branches: [ main ]
jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker build -t misperception/estanteria-bot:latest .

      - name: Push
        run: |
          docker login -u misperception - p ${{ secrets.DOCKER_PASS }}
          docker push misperception/estanteria-bot:latest

      - name: Run
        run: docker compose up -d
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Prune
        run: docker image prune -f